version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
       MYSQL_DATABASE: 'zeno'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'Mama199420'
       MYSQL_ROOT_PASSWORD: 'Mama199420'
